### ISSUE TITLE
Feature: Focus search bar in view

### ISSUE THREAD

**Issue by s-v-o** [fidley/VerticalTabs#35]
First of all great work, thank you very much for your effort.

It would be great if there would be a keyboard shortcut to switch to the VerticalTab view and focus the search bar. 
After that I would be able to enter some part of the name, press enter and the first entry would gain the focus and switch (back) to the editor.
So I'm able to quickly switch between many open editors.

**Comment by fidley** [comment]
Thanks! Very good idea! I'll work on it 🙂

W dniu pt., 1.09.2023 o 15:07 s-v-o ***@***.***> napisał(a):

**Comment by fidley** [comment]
@s-v-o any hint what could be the best key binding for this?

**Comment by s-v-o** [comment]
That's not an easy question as there are already so many key bindings in eclipse ;)
I think many of the "Open in..." bindings are bind to `CTRL+ALT`, so I would propse `CTRL+ALT+V`. 

Alternatively we could let it unbound and the user has to define.

**Comment by fidley** [comment]
![image](https://github.com/fidley/VerticalTabs/assets/7912195/4b3e3d39-c54e-406d-922d-4a94562a2b29)

**Comment by s-v-o** [comment]
Thank you very much for your prompt reply.
It seems to work fine when the view is already open.

A few comments:

Is it possible or planned to make the shortcut configurable?
![image](https://github.com/fidley/VerticalTabs/assets/64085779/87b8961e-1c77-4a5b-848f-041781f48eb6)

At the moment it only seems to work only, when the view is visible. When the view is hidden, it doesn't open automatically.

What I really like is that it would search automatically when I enter a string and that it searches for submatching strings (i.e. "world" finds "HelloWorld"). This is really something I wish all the eclipse views would do.

**Comment by fidley** [comment]
For configuration I need to see how to do it, never done it before, and what is strange is that, when I check what binding is done for Ctrl+Alt+V, then it shows the command, but not when searching as you do. I need to deep dive.

![image](https://github.com/fidley/VerticalTabs/assets/7912195/0191d4a5-dd24-4de6-b73a-77948edd627a)


Yes, you're right that the shortcut only works when the view is open. I did it on purpose, as in other case I was receiving exception that the view does not exists. I need to check if I can open the View from the code before - good hint again.

**Comment by fidley** [comment]
![image](https://github.com/fidley/VerticalTabs/assets/7912195/94bddcd5-b5e2-46c7-9e39-267319fe2a89)

**Comment by fidley** [comment]
Deployed

**Comment by s-v-o** [comment]
Thank you very much.

> Also view should appear now when you use the focus shortcut

This doesn't seem to work reliably. I think it opens the first time, when I use the shortcut and the view is hidden. After that the view does not appear again (but it works when I make the view visible).

**Comment by fidley** [comment]
Should be now solved
