### ISSUE TITLE
Add the ability to archive a group of tabs

### ISSUE THREAD

**Issue by Ronef** [fidley/VerticalTabs#40]
Sometimes i need to close all tabs in a group but later i need to restore all closed tabs.

So it will be very useful to do it in “one click” through the plugin:
1. Right click on a group → Archive → All group tabs have closed.
2. Right click on an archived group → Restore → All group tabs have opened in required order.

**Comment by fidley** [comment]
Currently when you close all tabs from the group -> the group is also closed.
What I could think about at the moment is to add new property for tab -> archived, which will mean I keep it in memory but it is not shown. When the group contains at least 1 archived tab, it will not be displayed. New Icon, or maybe an overlay would be needed to show that the group have archived tabs. Issues, I'm not sure it will be possible to restore the archived tabs after restarting of eclipse. This is to be checked.

**Comment by fidley** [comment]
@Ronef sorry that it takes so long, but I had not much motivation before ;)

Question, when you would "archive" group, would it be enough that all the tabs inside are marked as pinned and then closed?
They would still be visible on the tree.

**Comment by fidley** [comment]
![image](https://github.com/user-attachments/assets/9b924fb0-efde-40aa-b79a-8e09a557ba8e)
Pin and Close All + Open All
