### ISSUE TITLE
Add the ability to customize table columns

### ISSUE THREAD

**Issue by Ronef** [fidley/VerticalTabs#41]
I don't need the “C” column because i use hotkey or mouse middle click. Also i don't need the “Project” column.

So it will be cool to customize columns in the tabs view.

![image](https://github.com/fidley/VerticalTabs/assets/1333424/a33dfa90-5727-4d79-bb06-d5861fc94f5c)

**Comment by fidley** [comment]
I can imagine it can be useful :)

**Comment by fidley** [comment]
Done
