### ISSUE TITLE
Add the new column “Path” to the tabs view

### ISSUE THREAD

**Issue by Ronef** [fidley/VerticalTabs#42]
Sometimes several files have the same names (e. g. PSR-4):

![image](https://github.com/fidley/VerticalTabs/assets/1333424/97f44941-0ad4-4aaa-82f6-bb12eff4bb23)

So it will be useful to see paths of the tab files too.

I think this column should be optional, so the issue should be done after #41.

**Comment by fidley** [comment]
I think for now we have path as tooltip for file, but having possiblity to select column layout would make it possible to give more flexibility. It needs to come also with sorting sequence of course.

**Comment by fidley** [comment]
done
