### ISSUE TITLE
Add ctrl+double click to open object in another project

### ISSUE THREAD

**Issue by tomasz-grabarczyk** [fidley/VerticalTabs#43]
Hej Łukasz,

This is enhancement request.
I was wondering, if it would be feasible/doable to add an option to ctrl+double click on opened tab to show the window for selecting another project (same functionality as in _Favourites_ extension)? It would be great if there was an option to quickly open same object in another system instead of using _Open in Project_ from code view.
![image](https://github.com/fidley/VerticalTabs/assets/32244889/acae1211-0565-4d8e-8101-8c8be1862a82)

Another thing - do you think it would be possible to somehow hide the tabs above the editor, when using Vertical Tabs?
![image](https://github.com/fidley/VerticalTabs/assets/32244889/a2edcc7a-5a66-4b1e-a6ed-4b5466c395b2)

Thank you!

**Comment by fidley** [comment]
Hi Tomasz, 

Open in Project function is something ABAP/SAP Specific. So far Vertical tabs is made to be independent of the programming language, but I'll check if this can be for example a part of extension for the plugin, installed separately. 

I think also that the tabs above editor cannot be hidden, but I can also check that.
Cheers
Łukasz

**Comment by fidley** [comment]
I've created second feature with ABAP functions only with ctrl+double-click and open in project context menu

**Comment by fidley** [comment]
Hiding of tabs, I haven't found the way.
