### ISSUE TITLE
Highlight active tab

### ISSUE THREAD

**Issue by NordicAngel** [fidley/VerticalTabs#49]
Hello,
When selecting a tab, it is highlighted after being clicked but this dose not change when the active tab is change by other means. I would ask that active tab is show in VT properly, as having an inactive tab highlighted an be a bit confusing. 
Also having the active tab highlighted would help, when you have a lot of tabs open some with the same or simuler names.

**Comment by fidley** [comment]
Hi, 
very nice one. Will add it somehow :)

**Comment by fidley** [comment]
Added. Can be switched of in Preferences.
