### ISSUE TITLE
Problems switching tabs with same editor.

### ISSUE THREAD

**Issue by NordicAngel** [fidley/VerticalTabs#50]
Hello,
After an update/reinstall of eclipse I have been having problem switching between tabs. When i click on a tab in VT it will only show the last active tab with the editor of the chosen tab no matter witch of my tabs i choose.

**Comment by NordicAngel** [comment]
If I use the button "Open in project" it will change to the desired tab.

**Comment by fidley** [comment]
Are you able to record video of this behavior?

**Comment by fidley** [comment]
No need I could repeat it.

**Comment by fidley** [comment]
Update site will get new version in some seconds. Update and it will work again as it should.
