### ISSUE TITLE
Tab multi select dosen't work.

### ISSUE THREAD

**Issue by NordicAngel** [fidley/VerticalTabs#53]
Hello,
When "Select active tab" is enabled, ctrl + mouse 1 and shift + mouse 1, for selecting multiple tabs dosen't work.

**Comment by fidley** [comment]
Does work for me :(
![ctrl_mouse](https://github.com/user-attachments/assets/8cd03951-24c3-4d62-a005-07553c2724ff)

**Comment by NordicAngel** [comment]
Apparently it only happens when "Navigation to linked TAB by" is set to "selection".

**Comment by fidley** [comment]
You're right, although  you can still select, then the tabs are opened one by one and it makes troubles. I'll take a look on it.

**Comment by fidley** [comment]
Should work after this update
